server:
  port: 8080

spring:
  application:
    name: transactions-api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mendel.transactions: DEBUG